# версия docker-compose
version: "3.8"
services: 
  # приложение (API)
  app:
    # нахождение файлов программы
    build: 
      context: .
      dockerfile: Dockerfile
    # указание портов (хост:контейнер)
    ports: 
      - 8000:8000
    # указание контейнеров, от которых зависит 
    depends_on: 
      - M1
    # получить доступ к контейнеру с базой
    links:
      - M1
  
  # база данных
  M1:
  # базовый образ
    image: mysql
    # переменные окружения
    environment: 
    # пароль к базе
      - MYSQL_ROOT_PASSWORD=12345
    ports: 
    # указание портов (хост:контейнер)
      - 9992:3306
